version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env   #
    ports:
      - '${PORT}:${PORT}'
    command: npm run start:prod
    volumes:
      - .:/app
      - /app/node_modules